language: node_js
node_js:
  - "12.16"

branches:
  only:
    - master
    - prod

script: npm run-script build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $DEST_BUCKET
  skip_cleanup: true
  local_dir: build
  region: $S3_REGION
  on:
    - master
    - prod
